export const FETCH_COMPARISON_DATA = 'FETCH_COMPARISON_DATA';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SHOW_ONLY_DIFFERENCE = 'SHOW_ONLY_DIFFERENCES';